config/routes.rb
Recispeak::Application.routes.draw do
  resources :users do
    get 'input'
    post 'input_recipe'
    post 'input_ingredients'
    post 'input_directions'

    resources :recipes do 
      resources :recipe_comments
    end
    resources :recipe_books
    resources :recipe_book_entries
    resources :search
  end

  resources :recipes, only: [:index, :show]


  get '/session', to: 'session#new'
  post '/session', to: 'session#create'
  delete '/session', to: 'session#destroy'

  root 'welcome#index'
  get 'search' => 'search#search'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_comments
  has_many :ingredients, dependent: :destroy
  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :ingredients, reject_if: lambda { |a| a[:entry].blank? }, allow_destroy: true
  accepts_nested_attributes_for :steps, reject_if: lambda { |a| a[:instructions].blank? }, allow_destroy: true
  
  validates :title, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :load_user, except: [:index]
  before_action :load_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @websiterecipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    6.times { @recipe.ingredients.build}
    6.times { @recipe.steps.build}
  end

  def create
    @recipe = @user.recipes.new(recipe_params)

    if @recipe.save
      flash[:message] = "Recipe Created!"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @books = @user.recipe_books.all
    @ingredients = Ingredient.where(recipe_id: @recipe)
    @steps = Step.where(recipe_id: @recipe)
    @allsteps = []
    @steps.each do |step| 
      unless step.nil? 
        @allsteps << step.instructions
      end
    end
    @comments = RecipeComment.where(recipe_id: @recipe)
    render :show
  end

  def edit
    render :edit
  end

  def update
    @changed = @recipe.update(recipe_params)

    if @changed
      flash[:message] = "Recipe Updated!"
      redirect_to user_recipe_path(@recipe.user_id, @recipe.id)
    else 
      flash[:message] = "Recipe did not update!"
      redirect_to user_recipe_path(@recipe.user_id, @recipe.id)
    end
  end

  def destroy
    @recipe.destroy
    redirect_to user_path(@user)
  end

  private

  def load_user
    @user = User.find(current_user || params[:user_id])
  end

  def load_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:category, :title, :notes, ingredients_attributes: [:id, :entry, :_destroy], steps_attributes: [:id, :instructions, :_destroy]) 
  end

end

app/views/recipes/_form_new_recipe.html.erb
<div id="recipe-create-update">
<%= form_for [@user, @recipe] do |f| %>
  <%= f.text_field :category, placeholder:"Category", class:"form-add-recipe" %><br />
  <%= f.text_field :title, placeholder:"Title", class:"form-add-recipe" %><br />
  <br />

  <div id="ingredient-field">
    <%= f.fields_for :ingredients do |builder| %>
    <%= render "ingredient_fields", f: builder %>
    <% end %><br />
    <%= link_to_add_fields "Add Ingredient", f, :ingredients %><br />
  <br />
  </div>

  <div id="steps-field">
    <%= f.fields_for :steps do |builder| %>
    <%= render "step_fields", f: builder %>
    <% end %><br />
    <%= link_to_add_fields "Add Step", f, :steps %><br />
  <br />
  </div>

  <%= f.text_area :notes, placeholder:"Notes", rows:"3", cols: "65", class:"form-add-recipe" %><br />
  <%= f.submit @recipe.id.nil? ? "Create Recipe" : "Update Recipe", class:"splash-button" %>
<% end %>
</div>

app/views/recipes/_ingredient_fields.html.erb
<div class='fields'>
  <div id="ingredients">
    <%= f.text_field :entry, placeholder:"Ingredients", class:"form-add-recipe" %>
    <%= link_to_remove_fields "remove", f %>
  </div>
</div>

app/views/recipes/_step_fields.html.erb
<div class='fields'>
  <div id="steps">
    <%= f.text_field :instructions, placeholder:"Steps", class:"form-add-recipe" %>
    <%= link_to_remove_fields "remove", f %>
  </div>
</div>

app/views/recipes/edit.html.erb
  <div class="middle-container">
    <div class="center-titles">
    <div id="new-form">
        <h1>Add Recipe</h1>
      <%= render "form_new_recipe"%>
    </div>
  </div>
  </div>



<script>
  $(document).ready(function(){
    $('#new-form').toggle("slow");
  });
</script>

app/views/recipes/index.html.erb
<nav>
  <ul>
    <div class='nav-right'>
      <li><%= link_to "Back", root_path %></li>
    </div>
  </ul>
</nav>
  <div class="middle-container">
    <div class="center-titles">

      <div class="non-user-recipe-page">
        <h1> A list of our Recipes</h1>
        <hr></hr>
        <ul>
          <% @websiterecipes.each do |recipe| %>
          <li><%= link_to recipe.title, user_recipe_path(recipe.user_id, recipe.id) %></li>
          <hr></hr>
          <% end %>
        </ul>
        
      </div>
    </div>
  </div>
<script>
  function windowH() {
   var wH = $(window).height();

   $('.middle-container').css({height: wH});
}

windowH();
</script>

app/views/recipes/new.html.erb
<div class="middle-container">

  <div class='center-titles'>
    <form method="GET" action="/users/<%= @user.id%>/input" />
      <input type="text" name="address_input" class="recipe-url-input" placeholder="Paste Recipe From URL"/><br />
    </form>
  </div>

  <div id="new-form">
    <h3>Add Recipe</h3>
    <%= render "form_new_recipe"%>
  </div>
</div>



<script>
function windowH() {
   var wH = $(window).height();

   $('.middle-container').css({height: wH});
}

windowH();

  $(document).ready(function(){
    $('#new-form').toggle("slow");
  });   
</script>

app/views/recipes/show.html.erb
<% if session["user_id"].nil? %>
  <nav>
    <ul>
      <div class='nav-right'>
        <li><%= link_to "Back", root_path %></li>
      </div>
    </ul>
  </nav>
<% end %>

  <div class="middle-container">

    <div class="flash-message">
     <%= raw("<p>#{flash[:message]}</p>") unless flash[:message].nil? %>
    </div>
    
    <% unless session["user_id"].nil? %>
      <div class="add-recipe-to-book" title="Add to Recipe Book">
        <%= image_tag 'plus.png' %>
      </div>
    <% end %>

    <div class="book-options">
      <% if @books.empty? %>
      <p> You don't have any recipe books yet </p>
      <% else %>
      <%= form_for [@user, RecipeBookEntry.new] do |f| %>
      <%= hidden_field_tag :recipe_id, @recipe.id %>
      <%= select_tag :recipe_book_id, options_for_select(@books.collect{ |b| [b.title, b.id] }), class:"options-menu" %><br />
      <br />
      <%= f.submit "Save to Book" %>
      <% end %>
      <% end %>
    </div>

    <div class="center-titles">
      <h1><%= @recipe.title %></h1>
      <button id='start-reading' class='splash-button'>Begin</button>
    </div>

    <div class="recipe-containers">
      <h4>Ingredients</h4><br />
      <ul>
        <% @ingredients.each do |ingredient| %>
        <li><%= ingredient.entry %></li><br />
        <% end %>
      </ul>
    </div>

    <div class="recipe-containers">
      <h4>Directions</h4><br />
      <ul>
        <% @steps.each do |step| %>
        <li><%= step.instructions %></li><br />
        <% end %>
      </ul>
    </div>
    
    <div class="recipe-containers">
      <% unless session["user_id"].nil? %>
    <div class="comment-notes-links">
      <p class='comment-link'>Comments</p>
      <p class='note-link'>Notes</p>
    </div>
    <hr />
    <div class="note-section">
      <h4>Notes</h4>
      <p><%= @recipe.notes %></p>
      <% if @recipe.notes.nil? %>
      <br />
      <p>There are no notes yet for this recipe</p>
      <% end %>
    </div>

      <div class="comments-section">
        <h4>Comments</h4>
        <hr></hr>
        <% if @comments.empty? %>
          <p> There are no comments yet for this recipe <p>
        <% end %>
          <% @comments.each do |comment| %>
          <ul>
            <% @comment_user = User.find(comment.user_id) %>
            <li class="comments-left"><span class="username"><%= comment.created_at.strftime("%m/%d/%Y - %I:%M%p") %></span></li>
              <% if comment.user_id == session["user_id"] %>
                <span><form action="<%= user_recipe_recipe_comment_path(@user.id, @recipe.id, comment.id) %>" method="POST" class="recipe-display">
                <input type="hidden" name="_method" value="DELETE" />
                <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
                <button class='deletecomment'>delete comment</button></form></span> <br />
              <% end %>
            <br />
            <li class="comments-left">
              <%= image_tag @comment_user.profile_pic.url(:thumb) %>
              <span class="username"><%= @comment_user.first_name %>:</span>
              <em><%= comment.comments %></em>
            </li><br />

            
            <br><br />
            <hr></hr>
          </ul>
          <% end %>

          <%= form_for [@user, @recipe, RecipeComment.new] do |f| %>
            <%= hidden_field_tag :user_id, @user.id %>
            <%= text_area_tag :comments %><br />
            <%= f.submit "Submit Comment", class:"splash-button"%>
          <% end %><br />
      </div>
    </div>
<div class="update-link">
        <button class="splash-button"><%= link_to "Edit Recipe", edit_user_recipe_path(session["user_id"], @recipe) %></button>
      </div>
      <% end %>
  </div>


<script src="//cdnjs.cloudflare.com/ajax/libs/annyang/1.4.0/annyang.min.js">
</script>
<script>
  Recispeak.steps = <%= raw @allsteps %>;

  function windowH() {
   var wH = $(window).height();

   $('.middle-container').css({height: wH});
}

windowH();

  $('.add-recipe-to-book').click(function(){
    $('.book-options').fadeToggle("slow");
  });

  $('.note-link').click(function(){
    $('.note-section').show("slow", function(){
      $('.comments-section').hide("slow");
      $('.recipe-notes').css("height", "90%");
    });
  });

  $('.comment-link').click(function(){
    $('.comments-section').show("slow", function(){
      $('.note-section').hide("slow", function(){
          $('.recipe-notes').css("height", "90%");
      });
    });
  });

</script>


<%= javascript_include_tag "speech", "data-turbolinks-track" => true %>