config/routes.rb
Recispeak::Application.routes.draw do
  resources :users do
    get 'input'
    post 'input_recipe'
    post 'input_ingredients'
    post 'input_directions'

    resources :recipes do 
      resources :recipe_comments
    end
    resources :recipe_books
    resources :recipe_book_entries
    resources :search
  end

  resources :recipes, only: [:index, :show]


  get '/session', to: 'session#new'
  post '/session', to: 'session#create'
  delete '/session', to: 'session#destroy'

  root 'welcome#index'
  get 'search' => 'search#search'
end

app/models/user.rb
require 'nokogiri'
require 'open-uri'

class User < ActiveRecord::Base
  has_many :recipe_books
  has_many :recipe_comments
  has_many :recipes

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  self.has_secure_password()

  has_attached_file :profile_pic, :default_url => "chefatar.png",
                    :styles => {:thumb => "200x200#"},
                    :url => "/assets/users/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"

  validates_attachment_content_type :profile_pic, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg']
  validates_attachment_size :profile_pic, :less_than => 5.megabytes

  def is_admin?
    email == "nicholas@nick.com"
  end

  def get_ingredients_from_url(url)
    ingredients = Nokogiri::HTML(open(url)).css('li [itemprop="ingredients"]')
    return ingredients
  end

  def get_directions_from_url(url)
    directions = Nokogiri::HTML(open(url)).css('instructions', 'li span[class="plaincharacterwrap break"]', 'div [class="recipeDirections"] li', 'div [id="instructions"] li', 'li[class="instruction"]', 'div [class="instructions"] p', 'div[itemprop="instructions"] p', 'div[class="col12 directions"] p', 'div[itemprop="recipeInstructions"] p')
    return directions
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :authorize, only: [:show]

  def index
    if current_user.is_admin?
      @users = User.all
    else
      redirect_to user_path(current_user.id)
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session["user_id"] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def input
    @user = User.find(params[:user_id])
    @ingredients = get_ingredients_from_url(params[:address_input])

    @amounts = get_amounts_from_url(params[:address_input])

    @get_directions = []
    @get_directions << get_directions_from_url(params[:address_input])
    @directions = @get_directions.join("").split(".")

    if @ingredients.empty?
      @message_ingredient = "Ingredients Not Found"
    end
    if @directions.empty?
      @message_direction = "Directions Not Found"
    end

  end

  def input_recipe 
    @user = User.find(params[:user_id])
    @recipe = @user.recipes.create(title: params[:title] )
    @recipe.save
    render json: @recipe
  end

  def input_ingredients
    @ingredient = Ingredient.create(entry: params[:entry], recipe_id: params[:recipe_id])
    @ingredient.save
    render json: @ingredient
  end

  def input_directions
    @direction = Step.create(instructions: params[:instructions], recipe_id: params[:recipe_id])
    @direction.save
    render json: @direction
  end

  def show
    @recipe_book_entry = RecipeBookEntry.new
    @websiterecipes = Recipe.all
    @allbooks = RecipeBook.where(user_id: @user)
    @allrecipes = Recipe.where(user_id: @user)
    @allrecipes_on_recispeak = Recipe.all
  end

  def update
    @changed = @user.update(user_params)

    if @changed
      flash[:message] = "Updated Successfully"
      redirect_to user_path(@user.id)
    else
      flash[:message] = 'Update Failed!'
      redirect_to user_path(@user.id)
    end

  end

    def destroy
      @user.destroy
      session.destroy
      redirect_to root_path
    end

    private

    def load_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :facebook_url, :twitter_name, :address, :city, :state, :zipcode, :password, :password_confirmation, :birthday, :profile_pic)
    end

    def authenticate
      unless logged_in?
        redirect_to root_path
      end
    end

    def authorize
      unless current_user == @user
        redirect_to root_path
      end
    end

  def get_ingredients_from_url(url)
    ingredients = Nokogiri::HTML(open(url)).css('li [itemprop="ingredients"] > text()', 'span [itemprop="name"] > text()', 'span [class="ingredient-name"] > text()', 'span [itemprop="ingredients"] > text()', 'div [class="clrLeft"] > text()', 'ul [class="recipeIngredient"] li span > text()')
    if url.include?("thepioneerwoman" || "epicurious")
      ingredients.shift
      return ingredients
    else
      return ingredients
    end
  end

  def get_amounts_from_url(url)
    amounts = Nokogiri::HTML(open(url)).css('span [class="ingredient-amount"] > text()', 'span [itemprop="amount"] > text()')
    return amounts
  end

  def get_directions_from_url(url)
    directions = Nokogiri::HTML(open(url)).css('instructions > text()', 'li span[class="plaincharacterwrap break"] > text()', 'div [class="recipeDirections"] li > text()', 'div [id="instructions"] li > text()', 'li[class="instruction"] > text()', 'div [class="instructions"] p > text()', 'div[itemprop="instructions"] p > text()', 'div[class="col12 directions"] p > text()', 'div[itemprop="recipeInstructions"] p > text()', 'ol[itemprop="instructions"] li > text()', 'div [class="articleInstructionsDiv version1"] ol li > text()')
    return directions
  end

end

app/views/users/_form.html.erb
<div class='user-info-edit'>
<%= form_for @user do |f|%>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br />
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br />
  <%= f.label :email %>
  <%= f.email_field :email %><br />
  <%= f.label "phone number" %>
  <%= f.text_field :phone_number %><br />
  <%= f.label "facebook" %>
  <%= f.text_field :facebook_url%><br />
  <%= f.label "twitter"%>
  <%= f.text_field :twitter_name %><br />
  <%= f.label :street_address %>
  <%= f.text_field :address %><br />
  <%= f.label :city %>
  <%= f.text_field :city %><br />
  <%= f.label :state %>
  <%= f.text_field :state %><br />
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %><br />
  <%= f.label "password(required)" %>
  <%= f.password_field :password %><br />
  <%= f.label "password_confirmation(required)" %>
  <%= f.password_field :password_confirmation %><br />
  <%= f.label :birthday %>
  <%= f.date_field :birthday %><br />
  <%= f.label "Upload Picture"%>
  <%= f.file_field :profile_pic %><br />
  <%= f.submit "Save", class:"splash-button" %>
<% end %>
</div>

app/views/users/index.html.erb
  <div class="middle-container">
    <div class="center-titles">
      <h1> All Users</h1>

      <div class="non-user-recipe-page">
        <ul>
          <% @users.each do |user| %>
          <li><%= user.first_name %> <%= user.last_name %></li>
          <hr></hr>
          <% end %>
        </ul>
      </div>
      
    </div>
  </div>

app/views/users/input.html.erb
<div class="user-page-container">
  <div class="middle-container">
    
    <div class="center-titles">
      <button id='start-reading' class='user-menu-buttons-input'>Begin</button><hr></hr>

      <input placeholder="Enter A Title For Recipe", class="url-recipe-title" /><br />
      <button class="user-menu-buttons-input">Save Recipe To Recispeak&trade;</button>
    </div>

    <div class="recipe-information">
      <div class="page-left-recipe-container-url">
        <h2>Ingredients</h2><br />
        <ul>
          <li><%= @message_ingredient %></li>
          <% @ingredients.zip(@amounts).each do |item, amount| %>
          <li><%= amount %> <%= item %><li>
          <% end %>
        </ul>
      </div>

      <div class="page-right-recipe-container-url">
        <h2>Directions</h2><br />
        <ul>
          <li><%= @message_direction %></li>
          <% @directions.each do |direction| %>
          <li><%= direction %><li><br />
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</div>

<script>
  Recispeak.steps = <%= raw @directions %>;
</script>

<%= javascript_include_tag "speech", "data-turbolinks-track" => true %>
<%= javascript_include_tag "input", "data-turbolinks-track" => true %>

app/views/users/new.html.erb
<!DOCTYPE html>
<head>
  <title>Become a New Member</title>
</head>

<body>
  <% if session["user_id"].nil? %>
    <nav>
      <ul>
        <div class='nav-right'>
          <li><%= link_to "Back", root_path %></li>
        </div>
      </ul>
    </nav>
  <% end %>
    <div class="middle-container">
      <div class="logo-main-signup">
        <p>Recispeak<span style="color:white">&trade;</span></p>
      </div>

      <div id="new-form-user">
        <h3>Become a New Member</h3>
      <%= form_for @user do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %><br/>

        <%= f.label :last_name %>
        <%= f.text_field :last_name %><br/>

        <%= f.label :email %>
        <%= f.email_field :email %><br />

        <%= f.label :password %>
        <%= f.password_field :password %><br />

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br />
        <%= f.submit "Join"%>
      <% end %>
      </div>

    </div>

</body>

<script>
$(document).ready(function(){
  $("#new-form-user").toggle("slow");
});
</script>

app/views/users/show.html.erb
  <div class="middle-container-1">
    <div class="flash-message">
     <%= raw("<p>#{flash[:message]}</p>") unless flash[:message].nil? %>
    </div>

    <div class="page-left-container">
      <h3>Welcome <%= @user.first_name %></h3>
      <ul>
        <%= image_tag('chefatar.png') %>
        <li id="edit-profile">Edit Profile</li>
        <li><%= link_to "Recipe Books", user_recipe_books_path(@user) %></li>
        <li id="all-my-recipes">My Recipes</li>
        <li><%= link_to "Add Recipe", new_user_recipe_path(@user) %></li>
        <li id="all-recispeak-recipes">All Recispeak Recipes</li>
        <% if current_user.is_admin? %>
        <li><%= link_to "View All Users", users_path %></li>
      <% end %>
      </ul><br /> 
      <h4 style="font-style: italic">Recispeak.com</h4>
    </div>

    <div class="page-right-container">

      <div id="edit-form">
        <%= render "form" %>
      </div>

      <div id="all-user-recipes">
          <h2> Your Recipes </h2>
          <ul class="recipe-titles">
            <% @allrecipes.each do |recipe| %>
              <li><%= link_to recipe.title, user_recipe_path(recipe.user_id, recipe.id)%><span><form action="<%= user_recipe_path(recipe.user_id, recipe.id) %>" method="POST" class="recipe-display">
                <input type="hidden" name="_method" value="DELETE" />
                <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
                <button class='deletebutton'>x</button></form></span></li>            
            <% end %>
          </ul>
      </div>

      <div id="recispeak-recipe-list">
          <h2> All Recipes</h2>
          <ul class="recipe-titles">
            <% @allrecipes_on_recispeak.each do |recipe| %>
              <li><%= link_to recipe.title, user_recipe_path(recipe.user_id, recipe.id)%></li>           
            <% end %>
          </ul>
      </div>
</div>

<script>
function windowH() {
   var wH = $(window).height();

   $('.middle-container-1, .page-left-container, .page-right-container').css({height: wH});
}

windowH();

$(document).ready(function(){
  $(".page-left-container").hide(0).delay(10).fadeIn(500)
});

$(document).ready(function(){
  $(".page-right-container").hide(0).delay(10).fadeIn(500)
});

$('#edit-profile').click(function(){
  $('#edit-form').toggle("slow", function(){
    $('#all-user-recipes').hide("slow", function(){
      $('#recispeak-recipe-list').hide("slow")
    });
  });
});

$('#all-my-recipes').click(function(){
  $('#all-user-recipes').toggle("slow", function(){
    $('#edit-form').hide("slow", function(){
      $('#recispeak-recipe-list').hide("slow");
    });
  });
});


$('#all-recispeak-recipes').click(function(){
  $('#recispeak-recipe-list').toggle("slow", function(){
      $('#edit-form').hide("slow", function(){
          $('#all-user-recipes').hide("slow");
    });
  });
});

$('.input-site-info').click(function(){
  $('#compatible-sites').toggle("slow", function(){
    $('#welcome-blurb').hide("slow", function(){
      $('#edit-form').hide("slow", function(){
        $('#all-user-recipes').hide("slow", function(){
          $('#recispeak-recipe-list').hide("slow");
        });
      });
    });
  });    
});

</script>