config/routes.rb
Recispeak::Application.routes.draw do
  resources :users do
    get 'input'
    post 'input_recipe'
    post 'input_ingredients'
    post 'input_directions'

    resources :recipes do 
      resources :recipe_comments
    end
    resources :recipe_books
    resources :recipe_book_entries
    resources :search
  end

  resources :recipes, only: [:index, :show]


  get '/session', to: 'session#new'
  post '/session', to: 'session#create'
  delete '/session', to: 'session#destroy'

  root 'welcome#index'
  get 'search' => 'search#search'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :logged_in?
  
  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session["user_id"] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<head>
  <title>Recispeak.com&trade;</title>
  <%= javascript_include_tag "jquery.localscroll", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.scrollTo", "data-turbolinks-track" => true %>
</head>   
<body>
  <div class="page-container"> 
    <% if session["user_id"].nil? %>
    <nav>
      <div class="logintoggle">Login</div>
      <p id="splash-button-signup">Sign Up</p>
      <div class="flash-message-login">
        <%= raw("<p>#{flash[:message]}</p>") unless flash[:message].nil? %>
      </div>
      <p class="browse"><%= link_to "Browse Recipes", recipes_path %></p>
    </nav>
    <% end %>
    <div id="login">
      <% if session[:user_id].nil? %>
      <%= form_tag session_path do%>
      <%= label_tag "Email: " %><br />
      <%= text_field_tag :email%><br />
      <%= label_tag "Password: " %><br />
      <%= password_field_tag :password %><br /><br />
      <%= submit_tag "Sign In", class:"splash-button" %><br>
      <% end %>
      <% end %> 
    </div>
    <div id="new-form-user">
      <%= form_for @user do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %><br />

        <%= f.label :last_name %>
        <%= f.text_field :last_name %><br />

        <%= f.label :email %>
        <%= f.email_field :email %><br />

        <%= f.label :password %>
        <%= f.password_field :password %><br />

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br /><br />
        <%= f.submit "Join", class:"splash-button"%>
      <% end %>
      </div>
 </div>

  <div class="page-container-2">
    <div class="page-container-3">
      <p class="how-to-text">Guiding you through a recipe from start to finish... Here's How</p>
      <div class="how-to-images">
        <%= image_tag "tabletkitchen2.jpg" %><br />
        <p>Choose a recipe</p>
      </div>
      <div class="how-to-images">
        <%= image_tag "tabletkitchen.jpg" %><br />
        <p>Click Begin</p>
      </div>
      <div class="how-to-images">
        <%= image_tag "womannext.jpg" %><br />
        <p>Speak Command</p>
      </div>
      <div class="how-to-images">
        <%= image_tag "ipadcountertop.jpg" %><br />
        <p>Listen for Directions!</p>
      </div>
    </div>

    <div class="welcome-tag">
      <h1>Recispeak</h1>
      <h2>Let's talk food.</h2>
      <div class="social">
        <div class="facebook"></div>
        <div class="twitter"></div>
        <div class="pinterest"></div>
        <div class="linked"></div>
      </div>
    </div>
  </div>
  

<script>
$(document).ready(function(){
  $("#logo").hide(0).delay(10).fadeIn(2000)
});
$(".logintoggle").click(function(){
  $("#new-form-user").fadeOut("slow", function(){
      $("#login").slideToggle();
      });
    });
$("#splash-button-signup").click(function(){
      $("#login").fadeOut("slow", function(){
        $("#new-form-user").slideToggle();
      });
  });
$(window).scroll(function(){                          
            if ($(this).scrollTop() > $(window).height() - 50 && $(window).width() > 838){
                $('.welcome-tag').fadeIn(500);
            } else {
                $('.welcome-tag').fadeOut(500);
            }
        });

function windowH() {
   var wH = $(window).height();

   $('.page-container, .page-container-2').css({height: wH});
}

windowH();


</script>