config/routes.rb
Recispeak::Application.routes.draw do
  resources :users do
    get 'input'
    post 'input_recipe'
    post 'input_ingredients'
    post 'input_directions'

    resources :recipes do 
      resources :recipe_comments
    end
    resources :recipe_books
    resources :recipe_book_entries
    resources :search
  end

  resources :recipes, only: [:index, :show]


  get '/session', to: 'session#new'
  post '/session', to: 'session#create'
  delete '/session', to: 'session#destroy'

  root 'welcome#index'
  get 'search' => 'search#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recispeak</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Allura' rel='stylesheet' type='text/css'>
  <% unless @user.nil? %>
    <script>
    localStorage["user_id"] = <%= @user.id %>
    </script>
  <% end %>
</head>

<body>
  <% unless session["user_id"].nil? %>
  <div class='nav-middle'>
    <ul>
        <li><%= link_to "Home", user_path(session["user_id"]) %></li>
        <li><%= link_to "Books", user_recipe_books_path(session["user_id"]) %></li>
        <li><%= link_to "Search", user_search_index_path(session["user_id"]) %></li>
        <li><%= link_to "Log Out", "/session", method: "delete" %></li>
    </ul>
  </div>

  <% end %>
 
<%= yield %>
</body>
</html>